### ISSUE TITLE
I'm trying to use your plugin on laravel 5.6 and it's not working.

### ISSUE THREAD

**Issue by ovac** [Norris1z/hubtel-laravel-sms-channel#2]
I suggest that you test your app on different versions of laravel. Composer is unable to resolve a version for laravel 5.6.

**Comment by Norris1z** [comment]
The previous released supported the `5.6.*` version of `Illuminate/support` but the `5.5.*` version of `Illuminate/notifications`. I have updated the version of `Illuminate/notifications` to support `5.6` and released a version `1.2`  the plugin.

**Comment by Norris1z** [comment]
Thanks @ovac
