### ISSUE TITLE
I'm trying to use your plugin on laravel 5.8 and it's not working.

### ISSUE THREAD

**Issue by dela-dels** [Norris1z/hubtel-laravel-sms-channel#6]
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Notifications\Notifiable;

class Attendee extends Model
{
	use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected  $fillable = [
    	'lastname', 'firstname', 'phone', 'alt_phone', 'email', 'dob', 'location', 'school', 'gender'
    ];

	public function routeNotificationForSMS()
	{
	    return $this->phone; // where phone is a cloumn in your users table;
	}
}

```

This is my Model for attendees of a program.

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Notifications\Notification;

use NotificationChannels\Hubtel\HubtelChannel;

use NotificationChannels\Hubtel\HubtelMessage;

class SendConfirmationSMSController extends Notification
{
    public function via($notifiable)
    {
    	return [HubtelChannel::class];
    }

    public function toSMS($notifiable)
    {
    	return ( new HubtelMessage )
    						->from("The Program Hubb")
    						->content('Just Testing it out');
    }
}
```

This is my controller that sends the SMS.

what I have realized is that the message is not being sent to the recipient.

**Comment by Norris1z** [comment]
Does it throw an exception?

**Comment by Norris1z** [comment]
I think you should also read the latest notice in the changelog section of the readme.md which talks about IP whitelisting.

**Comment by dela-dels** [comment]
> Does it throw an exception?

Nah. it doesnt throw any exception. Surprisingly.

**Comment by dela-dels** [comment]
I'm developing and testing on my local machine at the moment. I haven't hosted it.

**Comment by Norris1z** [comment]
Have you published the config files? As in added the credentials to your `.env`?

**Comment by dela-dels** [comment]
> Have you published the config files? As in added the credentials to your `.env`?

Yes. I added the credentials to the.env files
didn't use the config file

**Comment by Norris1z** [comment]
Do you have enough sms balance in your hubtel account?

**Comment by dela-dels** [comment]
Lol Yes. GHS 10.00

> Do you have enough sms balance in your hubtel account?

LoL. Yes, I do. GHS 10.00 I think.

**Comment by Norris1z** [comment]
lol

**Comment by dela-dels** [comment]
so what's the way forward?
does everything look good in my controller and model?
I tried sending the number ass both +233 and normal 020 both didn't work.

**Comment by Norris1z** [comment]
Everything looks good to me. Check your sms reports on hubtel if the messages were sent actually or try using your credentials with postman just to confirm everything works fine.

**Comment by dela-dels** [comment]
Okay Sure. Will do that and give you feedback.

-----Original Message-----

**Comment by dela-dels** [comment]
@Norris1z Is is possible that me not saving the phone numbers as "+233......" be the issue?
Because numbers in my database are saved as 020, 024, etc.

**Comment by Norris1z** [comment]
> Okay Sure. Will do that and give you feedback.
> […](#)

Did you try this?

**Comment by Norris1z** [comment]
@dela-dels I created a new project to replicate the issue and it is true that the messages are not sent. In my case it was a `400 Bad Request` error. The problem is that the sender name must have no spaces and must be `11 characters` or less

```
From
string
REQUIRED
The sender address.Sender IDs must be 11 characters or less without spaces or 16 numbers.
```

**Comment by Norris1z** [comment]
Here's a link to `Hubtel's` SMS documentation

https://developers.hubtel.com/reference#send-message

Feel free to submit a PR to update the `README` with the necessary information.

Oh and don't forget to update the link in the `Available Message methods` section in the `README` as it is a dead link now.

**Comment by dela-dels** [comment]
> @dela-dels I created a new project to replicate the issue and it is true that the messages are not sent. In my case, it was a `400 Bad Request` error. The problem is that the sender name must have no spaces and must be `11 characters` or less
> 
> ```
> From
> string
> REQUIRED
> The sender address.Sender IDs must be 11 characters or less without spaces or 16 numbers.
> ```

So what did you do to resolve this? because changing my sender id to less than 11 characters still doesn't get the message sent

**Comment by Norris1z** [comment]
![WhatsApp Image 2019-04-15 at 1 00 19 PM (1)](https://user-images.githubusercontent.com/18237132/56134700-a4634d00-5f7e-11e9-9998-664dee8f3cad.jpeg)
![WhatsApp Image 2019-04-15 at 1 00 19 PM](https://user-images.githubusercontent.com/18237132/56134704-a6c5a700-5f7e-11e9-82db-4444892e562f.jpeg)

**Comment by Norris1z** [comment]
Reducing the characters worked for me

**Comment by dela-dels** [comment]
Doesn't work for me.

can I get a snippet of your implementation, please?

**Comment by Norris1z** [comment]
https://github.com/Norris1z/Hubtel-SMS-Test

**Comment by dela-dels** [comment]
After digging deep into the Laravel documentation as wells as the sample implementation you posted, I have been able to figure it out and it's working fine now.

All I needed to do was to tweak my implementation a bit to suit my requirements.

Thanks, @Norris1z for this package.
